Tablist:
  Header:
    - <color:#ff8045>CompletosCraft</color>
    - <color:#b85c32>Disfruta la estadia!</color>
  Footer:
    - <color:#ff8045>Servidor 1.20.x</color>
    - <color:#b85c32>mc.completoscraft.live</color>